version: "3"
services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/usr/share/nginx/html
    networks:
      - webnet
    restart: always

networks:
  webnet:
    driver: bridge
