/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DiscordBotImport } from './routes/discordBot'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const DiscordBotRoute = DiscordBotImport.update({
  id: '/discordBot',
  path: '/discordBot',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/discordBot': {
      id: '/discordBot'
      path: '/discordBot'
      fullPath: '/discordBot'
      preLoaderRoute: typeof DiscordBotImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discordBot': typeof DiscordBotRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discordBot': typeof DiscordBotRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/discordBot': typeof DiscordBotRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/discordBot'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/discordBot'
  id: '__root__' | '/' | '/discordBot'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscordBotRoute: typeof DiscordBotRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscordBotRoute: DiscordBotRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/discordBot"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/discordBot": {
      "filePath": "discordBot.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
